database.drivername=com.microsoft.sqlserver.jdbc.SQLServerDriver
database.url=jdbc:sqlserver://localhost:1433;databaseName=petDB;encrypt=true;trustServerCertificate=true
database.username=seren
database.password=1234