package com.pet.service.appointment;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import com.pet.dao.appointment.DailyScheduleRepository;
import com.pet.util.TimeSlotUtils;

import jakarta.transaction.Transactional;
import lombok.extern.slf4j.Slf4j;

/**
 * DailyScheduleService: 處理美容師班表的核心邏輯
 * 負責：計算可用空檔時段、每日自動產生班表排程
 */
@Service
@Slf4j
public class DailyScheduleService {
	@Autowired	
	private DailyScheduleRepository dailyScheduleRepository;
	
	/**
	 * 查詢指定日期所有美容師的 "可用空檔"
	 * @param date 日期
	 * @param totalDuration 預約總時長 (分鐘)，用來判斷連續空檔是否足夠
	 * @return List<Map> 包含美容師資訊與可用時段列表
	 */
	public List<Map<String, Object>> getAvailableTimeSlots(LocalDate date, int totalDuration) {
		
		System.out.println("====== [後端 Debug 開始] ======");
        System.out.println("查詢參數: 日期=" + date + ", 時長=" + totalDuration + ", 模式=");

        // 1. 從資料庫撈出當天所有排班資料 (包含 time_slots 字串 "001100...")
        List<Map<String, Object>> schedules = dailyScheduleRepository.findSchedulesByDate(date);
        
        System.out.println("資料庫撈到的班表數量: " + schedules.size());
        
        if (schedules.size() > 0) {
            System.out.println("第一筆資料內容: " + schedules.get(0));
        }
        
        // 2. 遍歷每位美容師的班表，計算可用空檔
        return schedules.stream()
            .map(row -> {
                // 從 Map 取值 (對應 SQL 查詢結果的欄位別名)
                Object id = row.get("groomerId"); 
                String name = (String) row.get("name");
                String timeSlots =  (String) row.get("timeSlots");

                // 3. 呼叫工具類別 (TimeSlotUtils) 分析 timeSlots 字串
                // 找出所有連續 "0" 長度大於等於 totalDuration 的區段，並轉為 HH:mm 格式
                List<String> availableTimes = TimeSlotUtils.findAvailableTimes(timeSlots, totalDuration);
                System.out.println("  -> 美容師 " + id + " 找到的空檔數量: " + availableTimes.size());
                
                // 4. 包裝成前端需要的 JSON 結構
                Map<String, Object> resultMap = new HashMap<>();
                resultMap.put("groomerId", id);
                resultMap.put("groomName", name);
                resultMap.put("slots", availableTimes);
                
                return resultMap;
            })
            // 5. 過濾掉完全沒有空檔的美容師，減少前端處理負擔
            .filter(map -> {
                List<?> times = (List<?>) map.get("slots");
                return times != null && !times.isEmpty();
            })
            .collect(Collectors.toList());
    }
	
	
    /**
     * 排程任務：每天凌晨 00:30 自動執行
     * 功能：自動補充未來的班表 (確保系統隨時都有未來 120 天的班表)
     */
	@Scheduled(cron = "0 30 0 * * ?") // Cron 表達式: 秒 分 時 日 月 週
    @Transactional
    public void autoGenerateDailySchedule() {
        log.info("=== 開始執行每日排班排程 ===");

        try {
            // 1. 計算目標日期：今天往後推 120 天
            // 系統入職時會產生 120 天，每天執行此排程補上第 121 天 (或者補足中間缺漏)
            LocalDate targetDate = LocalDate.now().plusDays(120);

            // 2. 呼叫資料庫 Stored Procedure 產生班表
            // GroomerId 傳 NULL -> SP 會對所有 "在職中" (is_active=1) 的美容師執行
            dailyScheduleRepository.generateGroomerSchedules(
                null,           // null 代表全體美容師
                targetDate,     // 起始日
                1,              // 只產生 1 天
                "09:00",        // 預設上班時間 (可依需求調整，這裡寫死)
                "21:00",        // 預設下班時間
                -1              // 每週公休日 (依需求調整，-1 代表無特定公休)
            );

            log.info("=== 每日排班排程執行成功，已產生 {} 的班表 ===", targetDate);

        } catch (Exception e) {
            log.error("每日排班排程執行失敗", e);
        }
    }
	
	/**
	 * 清除指定日期的排程快取 (目前已停用 Redis，此方法保留介面)
	 */
	public void evictScheduleCache(LocalDate date) {
		// Redis 已停用，此方法現在為空實作
		log.debug("快取功能已停用: {}", date);
	}
	
}