package com.pet.service.appointment;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import com.pet.dao.appointment.DailyScheduleRepository;
import com.pet.util.TimeSlotUtils;

import jakarta.transaction.Transactional;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class DailyScheduleService {
	@Autowired	
	private DailyScheduleRepository dailyScheduleRepository;

	
	public List<Map<String, Object>> getAvailableTimeSlots(LocalDate date, int totalDuration) {
		
		System.out.println("====== [後端 Debug 開始] ======");
        System.out.println("查詢參數: 日期=" + date + ", 時長=" + totalDuration + ", 模式=");

        List<Map<String, Object>> schedules = dailyScheduleRepository.findSchedulesByDate(date);
        
        System.out.println("資料庫撈到的班表數量: " + schedules.size());
        
        if (schedules.size() > 0) {
            System.out.println("第一筆資料內容: " + schedules.get(0));
        }
        
     // 2. 遍歷資料並計算空檔
        return schedules.stream()
            .map(row -> {
                // 從資料庫取值 (對應 SQL 裡的 AS 別名)
                // ⚠️ 注意：有些資料庫回傳 ID 會是 BigInteger，若報錯可改成 row.get("groomerId").toString()
                Object id = row.get("groomerId"); 
                String name = (String) row.get("name");
                String timeSlots =  (String) row.get("timeSlots");

                // 3. 呼叫工具類別計算「開始時間」
                List<String> availableTimes = TimeSlotUtils.findAvailableTimes(timeSlots, totalDuration);
                System.out.println("  -> 美容師 " + id + " 找到的空檔數量: " + availableTimes.size());
                // 4. 包裝成前端要的結構
                Map<String, Object> resultMap = new HashMap<>();
                resultMap.put("groomerId", id);
                resultMap.put("groomName", name);
                resultMap.put("slots", availableTimes);
                
                return resultMap;
            })
            // 5. 過濾掉沒有空檔的美容師
            .filter(map -> {
                List<?> times = (List<?>) map.get("slots");
                return times != null && !times.isEmpty();
            })
            .collect(Collectors.toList());
    }
	
	
	@Scheduled(cron = "0 30 0 * * ?") // Cron 表達式: 秒 分 時 日 月 週 (每天 00:30:00 執行)
    @Transactional
    public void autoGenerateDailySchedule() {
        log.info("=== 開始執行每日排班排程 ===");

        try {
            // 1. 計算目標日期：今天往後推 30 天 (也就是第 31 天)
            // 例如：今天是 1/1，plusDays(30) = 1/31。
            // 系統目前應該已經有到 1/30 的班表 (入職時產生的)，所以今天要補 1/31 的。
            LocalDate targetDate = LocalDate.now().plusDays(120);

            // 2. 呼叫 Stored Procedure
            // GroomerId 傳 NULL -> SP 裡面的邏輯會變成「跑所有 is_active = 1 的美容師」
            dailyScheduleRepository.generateGroomerSchedules(
                null,           // null 代表全體美容師
                targetDate,     // 起始日 (第 31 天)
                1,              // 只產生 1 天
                "09:00",        // 預設上班時間 (可依需求調整)
                "21:00",        // 預設下班時間
                -1              // 每週公休日 (依需求調整，-1 代表無)
            );

            log.info("=== 每日排班排程執行成功，已產生 {} 的班表 ===", targetDate);

        } catch (Exception e) {
            log.error("每日排班排程執行失敗", e);
        }
    }
	
	
}